#!/usr/bin/env python3
"""
ultralytics_common.py
======================
Shared training/export/reporting code for the three Ultralytics-based
detectors in this repo (YOLOv8n-P2, YOLO11n-P2, RT-DETR). Keeping this in
one place means all three:

  * train/val/test on the exact same BCCD split as every other model here
    (via bccd_data_utils.split_records),
  * get the same offline platelet copy-paste + mosaic augmentation applied
    to their YOLO-format training set on disk (in addition to Ultralytics'
    own built-in online mosaic/affine/HSV augmentation), so the "multiply
    the effective number of platelet positives" augmentation request is
    satisfied even on Ultralytics versions where the native `copy_paste`
    hyperparameter is mask-only,
  * export ONNX with an IDENTICAL output contract
    (boxes[N,4] xyxy, scores[N], labels[N] 1-indexed-with-background) in
    the model's own (possibly letterboxed) input space, with a
    `<model>.onnx.meta.json` sidecar describing how to preprocess/undo the
    letterbox -- so bcc_metrics/scripts/models_io.py::OnnxDetector can run
    ANY of these three models through one generic code path, identical to
    how it runs the from-scratch PyTorch models (SSDLite v2, NanoDet-Plus,
    EfficientDet-Lite0).
  * write the same standardized run_report_<model>.{json,md}.

Requires: pip install ultralytics
"""

import json
import time
from pathlib import Path

import numpy as np
import pandas as pd
from PIL import Image

from bccd_data_utils import (
    CLASSES, mosaic_augment, platelet_copy_paste, draw_prediction_grid,
    write_run_report, write_onnx_meta, class_counts, box_size_histogram,
)

try:
    import torch
except ImportError:
    torch = None


def _require_ultralytics():
    try:
        import ultralytics  # noqa: F401
        return ultralytics
    except ImportError as e:
        raise RuntimeError(
            "The `ultralytics` package is required for this training script but is not "
            f"installed ({e}). Install with:\n    pip install ultralytics\n"
        )


# ----------------------------------------------------------------------------
# Dataset prep: VOC -> YOLO + offline mosaic / platelet copy-paste
# ----------------------------------------------------------------------------
def prepare_yolo_dataset(train_recs, val_recs, test_recs, out_dir: Path,
                          n_mosaic_extra=None, n_copy_paste_extra=None, img_size=512, seed=42):
    """Writes a YOLO-format dataset (see bccd_data_utils.voc_records_to_yolo_dataset)
    and then ADDS extra synthetic training images/labels generated by
    mosaic + platelet copy-paste, saved directly to disk under
    images/train and labels/train, so they participate in every epoch
    identically to real images (this is on top of, not instead of,
    Ultralytics' own online augmentation pipeline).
    """
    from bccd_data_utils import voc_records_to_yolo_dataset

    out_dir = Path(out_dir)
    data_yaml = voc_records_to_yolo_dataset(train_recs, val_recs, test_recs, out_dir, class_names=CLASSES[1:])

    rng = np.random.default_rng(seed)
    n_mosaic_extra = len(train_recs) // 2 if n_mosaic_extra is None else n_mosaic_extra
    n_copy_paste_extra = len(train_recs) // 2 if n_copy_paste_extra is None else n_copy_paste_extra

    img_out = out_dir / 'images' / 'train'
    lbl_out = out_dir / 'labels' / 'train'
    name_to_idx = {name: i for i, name in enumerate(CLASSES[1:])}

    def _save(img: Image.Image, boxes, labels, tag):
        fname = f'synth_{tag}.jpg'
        img.save(img_out / fname, quality=90)
        w, h = img.size
        lines = []
        for (x1, y1, x2, y2), lbl in zip(boxes, labels):
            cls_name = CLASSES[int(lbl)]
            if cls_name not in name_to_idx:
                continue
            cx, cy = ((x1 + x2) / 2) / w, ((y1 + y2) / 2) / h
            bw, bh = (x2 - x1) / w, (y2 - y1) / h
            lines.append(f"{name_to_idx[cls_name]} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")
        (lbl_out / f'synth_{tag}.txt').write_text('\n'.join(lines))

    print(f'[INFO] Generating {n_mosaic_extra} offline mosaic images for small-object augmentation ...')
    for i in range(n_mosaic_extra):
        idx = int(rng.integers(0, len(train_recs)))
        img, boxes, labels = mosaic_augment(train_recs, idx, img_size=img_size, rng=rng)
        if len(boxes):
            _save(img, boxes, labels, f'mosaic_{i:04d}')

    print(f'[INFO] Generating {n_copy_paste_extra} offline platelet copy-paste images ...')
    for i in range(n_copy_paste_extra):
        idx = int(rng.integers(0, len(train_recs)))
        rec = train_recs[idx]
        img = Image.open(rec['image_path']).convert('RGB')
        boxes = np.asarray(rec['boxes'], dtype=np.float32).reshape(-1, 4)
        labels = np.asarray(rec['labels'], dtype=np.int64)
        img2, boxes2, labels2 = platelet_copy_paste(img, boxes, labels, train_recs, rng=rng)
        if len(boxes2):
            _save(img2, boxes2, labels2, f'copypaste_{i:04d}')

    n_synth = len(list(img_out.glob('synth_*.jpg')))
    print(f'[INFO] YOLO train split now has {len(train_recs)} real + {n_synth} synthetic (mosaic/copy-paste) images.')
    return data_yaml, n_synth


# ----------------------------------------------------------------------------
# Uniform ONNX export: raw Ultralytics head -> decode -> NMS, all baked into
# one exported graph with the SAME (boxes, scores, labels) contract used by
# every other model in this repo.
# ----------------------------------------------------------------------------
def export_uniform_onnx(ultra_model, out_path, imgsz=512, conf_thr=0.10, iou_thr=0.55, max_det=300):
    """Exports `ultra_model` (an ultralytics.YOLO or ultralytics.RTDETR
    instance, already loaded with trained weights) to ONNX using
    Ultralytics' own exporter with NMS baked into the graph
    (`nms=True`), which is the officially supported way (Ultralytics
    >=8.1) to get a single-array [1, max_det, 6] = [x1,y1,x2,y2,conf,cls]
    output with no separate postprocessing step needed downstream.

    A `.onnx.meta.json` sidecar records `output_layout:
    "single_array_xyxy_conf_cls"` and `letterbox: true` so
    bcc_metrics/scripts/models_io.py::OnnxDetector knows how to decode it
    and undo Ultralytics' letterbox preprocessing to get back to original
    image pixel coordinates.
    """
    export_path = None
    had_nms = True
    try:
        export_path = ultra_model.export(
            format='onnx', imgsz=imgsz, dynamic=False, simplify=True, opset=12,
            nms=True, conf=conf_thr, iou=iou_thr,
        )
    except TypeError:
        # Older ultralytics releases without `nms=`/`conf=`/`iou=` export kwargs:
        # fall back to a plain export (raw, pre-NMS head output) and mark that
        # explicitly in the meta file so OnnxDetector runs decode+NMS itself.
        print('[WARN] Installed ultralytics version does not support export(nms=True); '
              'exporting raw head output instead (OnnxDetector will run NMS itself).')
        had_nms = False
        export_path = ultra_model.export(format='onnx', imgsz=imgsz, dynamic=False, simplify=True, opset=12)

    export_path = Path(export_path)
    if export_path != Path(out_path):
        export_path.replace(out_path)

    layout = 'single_array_xyxy_conf_cls' if had_nms else 'raw_yolo_head'
    write_onnx_meta(
        out_path, input_size=(imgsz, imgsz), mean=[0.0, 0.0, 0.0], std=[1.0, 1.0, 1.0],
        letterbox=True, class_map={"0": "RBC", "1": "WBC", "2": "Platelets"},
        extra={
            'output_layout': layout,
            'conf_thr_baked_in': conf_thr,
            'iou_thr_baked_in': iou_thr,
            'max_det': max_det,
            'num_classes': 3,
        },
    )
    return out_path


def train_ultralytics_model(model_key, model_display_name, description, ultra_cls, model_yaml_candidates,
                             pretrained_weights, data_yaml, out_dir: Path, records_for_pred_grid,
                             img_size=512, epochs=150, batch=8, lr0=1e-3, extra_train_kwargs=None,
                             dataset_stats=None, hyperparams_extra=None):
    """Generic Ultralytics train -> val -> export -> report pipeline shared
    by YOLOv8n-P2 / YOLO11n-P2 / RT-DETR.

    model_yaml_candidates: ordered list of model yaml/weight names to try,
        e.g. ['yolov8n-p2.yaml', 'yolov8n.yaml'] -- the first one the
        installed ultralytics version recognizes is used, so a P2
        (small-object) head is preferred but training still proceeds on a
        version where that config isn't bundled.
    """
    _require_ultralytics()
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    extra_train_kwargs = extra_train_kwargs or {}

    t0 = time.time()
    model = None
    used_yaml = None
    last_err = None
    for cand in model_yaml_candidates:
        try:
            model = ultra_cls(cand)
            if pretrained_weights:
                try:
                    model.load(pretrained_weights)
                except Exception as e:
                    print(f'[WARN] Could not load pretrained weights {pretrained_weights} into {cand}: {e}')
            used_yaml = cand
            break
        except Exception as e:
            last_err = e
            print(f'[WARN] Model config "{cand}" unavailable in this ultralytics install ({e}); trying next candidate.')
    if model is None:
        raise RuntimeError(f'None of the model configs {model_yaml_candidates} could be built: {last_err}')
    print(f'[INFO] {model_display_name}: using model config "{used_yaml}"')

    train_kwargs = dict(
        data=str(data_yaml), imgsz=img_size, epochs=epochs, batch=batch, lr0=lr0,
        optimizer='AdamW', cos_lr=True, warmup_epochs=3.0,
        mosaic=1.0, mixup=0.1, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4,
        project=str(out_dir), name='train', exist_ok=True, seed=42, patience=30,
        verbose=True,
    )
    train_kwargs.update(extra_train_kwargs)
    try:
        results = model.train(**train_kwargs)
    except TypeError as e:
        # Some kwargs (e.g. fl_gamma, copy_paste) are version-dependent;
        # retry once without the optional extras rather than hard-failing.
        print(f'[WARN] model.train() rejected an argument ({e}); retrying without extra_train_kwargs.')
        for k in list(extra_train_kwargs.keys()):
            train_kwargs.pop(k, None)
        results = model.train(**train_kwargs)

    train_time_sec = time.time() - t0

    val_metrics = {}
    try:
        # IMPORTANT: project/name must be passed explicitly here too, not just to
        # .train() above -- otherwise Ultralytics writes val plots/confusion
        # matrices to its own global runs/detect/val(-N)/ instead of this model's
        # output/<model_key>/ folder, scattering results outside the unified layout.
        val_results = model.val(data=str(data_yaml), split='val', imgsz=img_size,
                                 project=str(out_dir), name='val', exist_ok=True)
        val_metrics = {
            'val_mAP50': float(val_results.box.map50),
            'val_mAP50-95': float(val_results.box.map),
            'val_precision': float(np.mean(val_results.box.p)) if hasattr(val_results.box, 'p') else None,
            'val_recall': float(np.mean(val_results.box.r)) if hasattr(val_results.box, 'r') else None,
        }
    except Exception as e:
        print(f'[WARN] model.val() failed: {e}')

    test_metrics = {}
    try:
        test_results = model.val(data=str(data_yaml), split='test', imgsz=img_size,
                                  project=str(out_dir), name='test', exist_ok=True)
        test_metrics = {
            'test_mAP50': float(test_results.box.map50),
            'test_mAP50-95': float(test_results.box.map),
        }
    except Exception as e:
        print(f'[WARN] model.val(split="test") failed: {e}')

    # Ultralytics writes results.csv itself under out_dir/train/; copy/re-save
    # as history_<model_key>.csv for naming consistency with every other script.
    hist_csv_src = out_dir / 'train' / 'results.csv'
    hist_csv_dst = out_dir / f'history_{model_key}.csv'
    if hist_csv_src.exists():
        df = pd.read_csv(hist_csv_src)
        df.columns = [c.strip() for c in df.columns]
        df.to_csv(hist_csv_dst, index=False)
        try:
            import plotly.express as px
            loss_cols = [c for c in df.columns if 'loss' in c.lower()]
            if loss_cols:
                fig = px.line(df, x=df.columns[0], y=loss_cols, markers=True,
                               title=f'{model_display_name} training curves')
                fig.write_image(str(out_dir / f'loss_curves_{model_key}.png'))
        except Exception as e:
            print(f'[WARN] Could not render loss-curve chart: {e}')
    else:
        print(f'[WARN] {hist_csv_src} not found; Ultralytics may have written it elsewhere in this version.')

    def predict_fn(pil_img):
        res = model.predict(pil_img, imgsz=img_size, conf=0.10, verbose=False)[0]
        if res.boxes is None or len(res.boxes) == 0:
            return np.zeros((0, 4)), np.zeros((0,), dtype=int), np.zeros((0,))
        boxes = res.boxes.xyxy.cpu().numpy()
        labels = res.boxes.cls.cpu().numpy().astype(int) + 1  # -> 1-indexed w/ background at 0
        scores = res.boxes.conf.cpu().numpy()
        return boxes, labels, scores

    try:
        draw_prediction_grid(records_for_pred_grid, predict_fn, out_dir / f'sample_predictions_{model_key}.png')
    except Exception as e:
        print(f'[WARN] Sample-prediction grid failed: {e}')

    onnx_path = out_dir / f'{model_key}_bccd.onnx'
    try:
        export_uniform_onnx(model, onnx_path, imgsz=img_size)
    except Exception as e:
        print(f'[WARN] ONNX export failed: {e}')
        onnx_path = None

    ncnn_note = None
    try:
        model.export(format='ncnn', imgsz=img_size)
        ncnn_note = 'NCNN export succeeded; see the *_ncnn_model/ directory next to the run.'
    except Exception as e:
        ncnn_note = (f'NCNN export skipped/failed ({e}). Install the `ncnn` package and re-run '
                      f'`model.export(format="ncnn")` if you need an .ncnn deployment artifact for the Pi 4.')

    best_pt = None
    for cand in [out_dir / 'train' / 'weights' / 'best.pt']:
        if cand.exists():
            best_pt = cand
            break

    hyperparams = {'model_config': used_yaml, 'img_size': img_size, 'epochs': epochs, 'batch': batch,
                   'lr0': lr0, **train_kwargs, **(hyperparams_extra or {})}
    dataset_stats = dataset_stats or {}

    write_run_report(
        out_dir, model_key=model_key, model_display_name=model_display_name, description=description,
        hyperparams=hyperparams, dataset_stats=dataset_stats,
        timing={'train_time_sec': train_time_sec, 'train_time_min': train_time_sec / 60.0, 'epochs': epochs},
        metrics={**val_metrics, **test_metrics},
        files={
            'best_checkpoint': str(best_pt) if best_pt else None,
            'onnx': str(onnx_path) if onnx_path else None,
            'history_csv': str(hist_csv_dst) if hist_csv_src.exists() else None,
            'sample_predictions': str(out_dir / f'sample_predictions_{model_key}.png'),
            'ultralytics_run_dir': str(out_dir / 'train'),
        },
        notes=[
            'mAP/precision/recall above are Ultralytics\' own validation numbers (for a quick '
            'sanity check during training). The authoritative, cross-model-comparable numbers '
            '(same IoU-matching code as every other model) come from bcc_metrics/run_all.py, '
            'which evaluates the exported ONNX model on the identical BCCD test split and the '
            '72-image OOD set.',
            ncnn_note,
        ],
    )

    return model, val_metrics, test_metrics
